packages:
  - .

catalogs:
  prod:
    '@vueuse/core': 14.0.0
    lucide: ^0.554.0
    lucide-vue-next: ^0.554.0
    naive-ui: ^2.42.0
    vue: ^3.5.25
    vue-router: ^4.6.3
  dev:
    '@antfu/eslint-config': ^4.16.2
    '@tsconfig/node24': ^24.0.3
    '@types/jsdom': ^27.0.0
    '@types/lodash-es': ^4.17.12
    '@types/node': ^24.10.1
    '@unocss/preset-wind4': ^66.5.9
    '@vitejs/plugin-vue': ^6.0.2
    '@vitejs/plugin-vue-jsx': ^5.1.2
    '@vitest/eslint-plugin': ^1.5.0
    '@vue/eslint-config-typescript': ^14.6.0
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    clsx: ^2.1.1
    eslint: ^9.39.1
    eslint-plugin-oxlint: ~1.29.0
    eslint-plugin-vue: ~10.5.1
    jiti: ^2.6.1
    jsdom: ^27.2.0
    lodash-es: ^4.17.21
    mockfly: 1.2.2
    npm-run-all2: ^8.0.4
    oxlint: ~1.29.0
    tailwind-merge: ^3.4.0
    typescript: ~5.9.0
    unocss: ^66.3.3
    'unplugin-icons': "22.5.0"
    vite: npm:rolldown-vite@latest
    vite-plugin-vue-devtools: ^8.0.5
    vitest: ^4.0.14
    vue-tsc: ^3.1.5

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
